export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_RECEIVED = 'METRICS_RECEIVED'
export const GET_LAST_THIRTY_MINS_DATA = 'GET_LAST_THIRTY_MINS_DATA'
export const METRICS_RECEIVED_MULTI = 'METRICS_RECEIVED_MULTI'
export const TRIGGER_LIVE_UPDATES = 'TRIGGER_LIVE_UPDATES'
